const data = {
  techs: [
    {
      _id: "1",
      name: "tech 1 name",
      image: "./images/1.jpg",
      services: "services tech offers",
      book: "link to booking app",
      phone: "+1-541-000-0001",
      email: "email1@email.com.com",
      instagram: "http://www.instagram.com",
      facebook: "https://www.facebook.com",
    },
    {
      _id: "2",
      name: "tech 2 name",
      image: "../images/1.jpg",
      services: "services tech offers",
      book: "link to booking app",
      phone: "+1-541-000-0002",
      email: "email2@email.com.com",
      instagram: "http://www.instagram.com",
      facebook: "https://www.facebook.com",
    },
    {
      _id: "3",
      name: "tech 3 name",
      image: "../images/2.jpg",
      services: "services tech offers",
      book: "link to booking app",
      phone: "+1-541-000-0003",
      email: "email3@email.com.com",
      instagram: "http://www.instagram.com",
      facebook: "https://www.facebook.com",
    },
    {
      _id: "4",
      name: "tech 4 name",
      image: "../images/3.jpg",
      services: "services tech offers",
      book: "link to booking app",
      phone: "+1-541-000-00014",
      email: "email4@email.com.com",
      instagram: "http://www.instagram.com",
      facebook: "https://www.facebook.com",
    },
    {
      _id: "5",
      name: "tech 5 name",
      image: "../images/4.jpg",
      services: "nails",
      book: "link to booking app",
      phone: "+1-541-000-0005",
      email: "email4@email.com.com",
      instagram: "http://www.instagram.com",
      facebook: "https://www.facebook.com",
    },
  ],
};
export default data;
